branch protection (#25)
* try deleting images this way

* delete images in main

* add branch protection workflow for main

diff --git a/.github/workflows/verify-main.yaml b/.github/workflows/verify-main.yaml
--- a/.github/workflows/verify-main.yaml
+++ b/.github/workflows/verify-main.yaml
@@ -8,6 +8,14 @@ env:
   TF_WORKSPACE_NAME: production
 
 jobs:
+  check_branch:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check branch
+        if: github.head_ref != 'staging'
+        run: |
+          echo "ERROR: You can only merge to main from staging!"
+          exit 1
   mvn-verify:
     runs-on: ubuntu-latest
     steps:
